name: <CI> Demo Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  demo_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Update pip
        run: |
          python -m pip install --upgrade pip
        shell: bash
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m pip install nbmake

      - name: Run demo check
        run: |
          python -m pytest --nbmake -v demos/